### ISSUE TITLE
Oak Ridge National Lab Loblolly: ISCN 3.5 Review

### ISSUE THREAD

**Issue by lilly-heran** [ISCN/SOCDRaHR2#22]
- [x] Evaluate dataset
- [x] merge study data
- [x] clean up profile data
- [x] clean up layer data
- [x] make graphics
- [x] Write up summary report narrative 
- [x] Good commenting
- [x] External review by someone else

**Comment by lilly-heran** [comment]
Cleaned up raw data. Fixed problems with "NA" data and gapfilling. aa0e306dbec4cea5c0bbe7c64817c7a9272517ba

**Comment by lilly-heran** [comment]
Starting comments and narratives. ae42762ad537386d42d37c3e721dac4ec249d6d8

**Comment by lilly-heran** [comment]
Finishing comments and narratives. 5d939987e4d66a2d9f9d578a59ed51e452ba2c41

**Comment by lilly-heran** [comment]
Added doi link to the citation, referenced in the cryptic message, to the top narrative. 7013c6d89e9a99f80a846747cffede5b2ae97780

**Comment by ktoddbrown** [comment]
Fixes:

- [x] Remove the #  at the top of the report https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/104_OakRidgeNationalLab_Loblolly_DWJ.Rmd#L3 this is better expressed as a straight paragraph. Outside a r-chunk the # signals a section header. Similar issues throughout the document.
- [x] keep the remeasured values https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/104_OakRidgeNationalLab_Loblolly_DWJ.Rmd#L41
- [x] Reformat https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/104_OakRidgeNationalLab_Loblolly_DWJ.Rmd#L55 1) print transpose of the dataset_study 2) move the tables and figures to their own files. See https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/101_HeckmanLithosequence.Rmd#L49-L65 
- [x] mute messages and warnings in your chucks similar to https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/101_HeckmanLithosequence.Rmd#L49

**Comment by lilly-heran** [comment]
Began working on the "fixes" stated above. Removed #'s at the beginning of the markdown, began to reformat, kept the remeasured values (the only bd is kept right now, need to specify in the meeting if all should be kept @ktoddbrown ), muted messages and warnings, and added some todo/ clarification needed items at the bottom of the document. 2a70e4220e4a3a6448bd574c322d1421d8af3f8c

**Comment by annedavin** [comment]
@ktoddbrown This dataset should be ready to review.
