### ISSUE TITLE
Johnson2011 Alaska Deep soil carbon

### ISSUE THREAD

**Issue by ktoddbrown** [ISCN/SOCDRaHR2#25]
- [x]  Evaluate dataset
- [x]  merge study data
- [ ]  clean up profile data
- [ ]  clean up layer data
- [ ]  make graphics
- [ ]  Write up summary report narrative
- [ ]  Good commenting
- [ ]  External review by someone else

**Comment by ktoddbrown** [comment]
First pass here, but needs to be double checked. da3b1b8f2985244247db8a7c8a63e01e00b0b72e

**Comment by annedavin** [comment]
duplicate issue, #77
