### ISSUE TITLE
Buell 2004: USGS ‘S3C’ (Site-specific soil C) database

### ISSUE THREAD

**Issue by ktoddbrown** [ISCN/SOCDRaHR2#26]
- [x]  Evaluate dataset
- [x]  merge study data
- [ ]  clean up profile data
- [ ]  clean up layer data
- [ ]  make graphics
- [ ]  Write up summary report narrative
- [ ]  Good commenting
- [ ]  External review by someone else

see d6d4e6a8821e9ae402e413f0c2b1b065dc7a1f29

**Comment by annedavin** [comment]
duplicate, #72
