### ISSUE TITLE
Hugelius 2013 Northern Circumpolar Soil Carbon database

### ISSUE THREAD

**Issue by ktoddbrown** [ISCN/SOCDRaHR2#27]
- [x]  Evaluate dataset
- [x]  merge study data
- [x]  clean up profile data
- [x]  clean up layer data
- [ ]  make graphics
- [ ]  Write up summary report narrative
- [ ]  Good commenting
- [ ]  External review by someone else

**Comment by annedavin** [comment]
duplicate issue, see #83
