### ISSUE TITLE
Permafrost Carbon Network RCN data

### ISSUE THREAD

**Issue by ktoddbrown** [ISCN/SOCDRaHR2#28]
- [x]  Evaluate dataset
- [ ]  merge with profile level contributions
- [ ]  figure out citation/referencing/study level attributions
- [ ]  merge study data
- [ ]  clean up profile data
- [ ]  clean up layer data
- [ ]  make graphics
- [ ]  Write up summary report narrative
- [ ]  Good commenting
- [ ]  External review by someone else

**Comment by ritahippe** [comment]
@ktoddbrown 
Awaiting review on Permafrost markdown in 79729bf . Included comments on whether or not the Permafrost-specific code seemed to work for other datasets (which could possibly replace some Template code and make the Template better-handle the Permafrost dataset).

Also awaiting review on citation format (there were many) in 2ea7f16
