### ISSUE TITLE
ISCN load runtime

### ISSUE THREAD

**Issue by ktoddbrown** [ISCN/SOCDRaHR2#3]
The ISCN database takes a long time to load. Is there anyway to speed this up?

bce72b2a765c901f0e684950ebaa57f5ed9ba358

Also looking for ways to reduce the file size.

**Comment by bpbond** [comment]
Can you send the file(s) you're using to me so I can do some testing?

**Comment by ktoddbrown** [comment]
You'll need to download them here http://iscn.fluxdata.org/data/access-data/database-reports/ It's too big for me to send directly. You are looking for the ISCN_ALL-DATA_LAYER_C*_1-1 Layer files and the meta data files are here http://iscn.fluxdata.org/data/dataset-information/data-documentation/

**Comment by bpbond** [comment]
OMG they're 20+MB Excel files?!? Seriously? OK, downloading, thanks.

**Comment by ktoddbrown** [comment]
Yep, they are big mothers. I got the final R dataframe down to under 180Mb and was pretty happy with that but it does reach around 400Mb when processing unfortunately.

**Comment by bpbond** [comment]
Hey, can you give me an example of calling `processData_ISCN3`? I'm having trouble getting it to run.

Looking through the code, though, I see two immediate speedup possibilities.
1. There's a bunch of calls to `read_excel` and `read_csv` that are followed by `select` calls. If there are columns you know you don't want, it would be faster to never read them at all, i.e. use the `col_types` parameter to "skip" columns.
2. Lines 99, 106, and 143 `bind_rows` inside a loop, which can get very expensive. If this is costing significant time (check using the Profile tool), store the results in a list and bind _once_ at the end:
```R
sample <- list()
for(fileName in files.arr) {
  ...
 sample[[fileName]] <- ... 
}
return(list(sample = bind_rows(sample), ...)
```

**Comment by ktoddbrown** [comment]
Check out here: https://github.com/ktoddbrown/soils-long-tail-recovery/blob/master/reports/ISCNVisualize.Rmd you'll also need the key here: https://github.com/ktoddbrown/soils-long-tail-recovery/blob/master/dataset_keys/ISCNKey.xlsx (BTW we need to add readr::cols to the import list for this function, just tried to rerun things and ran into this).

1) We could recode the reads to just pull in the study and field dataframes seperately and duplicate the read_csv function. I didn't think that would save a whole bunch of time since it's a read instead of a select but I'm open to trying it.

2) While most of the time I agree with you about the bind_rows that's not the expensive part of the command like there. The spread/gather/joins are what is killing us. I tried coding it as a do and it was not any better. Again, I'm happy to try and compare the run time. Keep in mind that these are BIG files too.

**Comment by ktoddbrown** [comment]
A side note, if we are going to process the headers first we could also go back to read_excel and parse the type of the columns. The observation_date was reading badly so I went back to read_csv but that requires people to export the downloaded table to csv before processing.

**Comment by ktoddbrown** [comment]
Resolved with more recent packages of R. Closing.
