### ISSUE TITLE
Ping 2010 LuPima

### ISSUE THREAD

**Issue by ktoddbrown** [ISCN/SOCDRaHR2#30]
- [x] Evaluate dataset
- [x]  merge study data
- [x]  clean up profile data
- [x]  clean up layer data
- [x]  make graphics
- [x]  Write up summary report narrative
- [x]  Good commenting
- [x]  External review by someone else

**Comment by ktoddbrown** [comment]
- [x] Remove the header information since this is going to be run as bookdown object https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L1-L6
- [x] https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L44 We actually want to keep the ISCN gap filled rows in general, we just want to remove the soc values that were calculated. Think about using a `mutate` with an `case_when` to recode the ISCN derived SOC values and associated method notes. similar to https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L49-L52
- [x] Add a space after your `#` so that this shows up as a header https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L59
- [x] Add a narration about what you had to do to clean up this dataset, put it before your table section and base it loosely on this: https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/101_HeckmanLithosequence.Rmd#L45-L47
- [x] remove the name from the chunk https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L102 and break out each figure into it's own chunk.

I was going to have you rewrite this: https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L23-L27 but in retrospect I really like this solution! I'm going to move this to the index.Rmd file and make sure to round all the date columns when we read in the files.

**Comment by ktoddbrown** [comment]
- [x] Country flag is actually set for LuPima so you need to remove https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L42 and https://github.com/ISCN/SOCDRaHR2/blob/c1ae01bbd91f32cf95f3c995e8288b4f09d2b785/data_reports/103_LuPima.Rmd#L49

**Comment by ktoddbrown** [comment]
See 08368f5 for the new modification date standardizations!

**Comment by juliebielecki** [comment]
Merged to master branch
